In [1]:
import numpy as np

# Predetermined stock price matrices (5 days x 3 features: Open, High, Low)
stock1 = np.array([
    [100, 105, 99],
    [102, 107, 101],
    [104, 109, 103],
    [103, 108, 102],
    [105, 110, 104]
])

stock2 = np.array([
    [98, 103, 97],
    [101, 106, 100],
    [103, 108, 102],
    [102, 107, 101],
    [104, 109, 103]
])

# Element-wise sum
sum_matrix = stock1 + stock2

# Element-wise difference
diff_matrix = stock1 - stock2

# Display results
print("Stock 1:\n", stock1)
print("\nStock 2:\n", stock2)
print("\nElement-wise Sum:\n", sum_matrix)
print("\nElement-wise Difference:\n", diff_matrix)

Stock 1:
 [[100 105  99]
 [102 107 101]
 [104 109 103]
 [103 108 102]
 [105 110 104]]

Stock 2:
 [[ 98 103  97]
 [101 106 100]
 [103 108 102]
 [102 107 101]
 [104 109 103]]

Element-wise Sum:
 [[198 208 196]
 [203 213 201]
 [207 217 205]
 [205 215 203]
 [209 219 207]]

Element-wise Difference:
 [[2 2 2]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
